# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfsuit < Formula
  desc "Fast, opinionated Terraform naming linter & fixer"
  homepage "https://github.com/josdagaro/tfsuit"
  version "1.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josdagaro/tfsuit/releases/download/v1.7.0/tfsuit_1.7.0_darwin_amd64.tar.gz"
      sha256 "2a39ed20cab0150876512268c991eb2bea66a527333759a65ecb877d11e87c0c"

      def install
        bin.install "tfsuit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josdagaro/tfsuit/releases/download/v1.7.0/tfsuit_1.7.0_darwin_arm64.tar.gz"
      sha256 "a38fd46b7c0caa7f527c7971dd40f2190ecaf3ec166fdabe1281cfafef45bbf4"

      def install
        bin.install "tfsuit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josdagaro/tfsuit/releases/download/v1.7.0/tfsuit_1.7.0_linux_amd64.tar.gz"
      sha256 "a1c235ca6a800e5c86244b9a67f147bb33c01531a34109c67572dfaf0241843a"
      def install
        bin.install "tfsuit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josdagaro/tfsuit/releases/download/v1.7.0/tfsuit_1.7.0_linux_arm64.tar.gz"
      sha256 "bbd52665b5b68f8d2ba95ba04709da77cb30b6426a0a1a5505f23f011a3aaf82"
      def install
        bin.install "tfsuit"
      end
    end
  end

  test do
    tfsuit --help
  end
end
