# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfsuit < Formula
  desc "Fast, opinionated Terraform naming linter & fixer"
  homepage "https://github.com/josdagaro/tfsuit"
  version "1.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josdagaro/tfsuit/releases/download/v1.4.1/tfsuit_1.4.1_darwin_amd64.tar.gz"
      sha256 "d3cdbd3a27a804b68af4e159da56e8e2d2286347c75426c75e43e1e38aeb0778"

      def install
        bin.install "tfsuit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josdagaro/tfsuit/releases/download/v1.4.1/tfsuit_1.4.1_darwin_arm64.tar.gz"
      sha256 "66f54fcb23f43d1238fbbfd0163a7094d17b558ceb9371b24bf18733dc19d492"

      def install
        bin.install "tfsuit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josdagaro/tfsuit/releases/download/v1.4.1/tfsuit_1.4.1_linux_amd64.tar.gz"
      sha256 "f07e82238fb7be992f9c383429b783f7272e4da5be6c58650daeaf7c737c8b8d"
      def install
        bin.install "tfsuit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josdagaro/tfsuit/releases/download/v1.4.1/tfsuit_1.4.1_linux_arm64.tar.gz"
      sha256 "fd65311eca08688e03e4c883fa4548e66e50b18a076970b61efb9e758d07849f"
      def install
        bin.install "tfsuit"
      end
    end
  end

  test do
    tfsuit --help
  end
end
