# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfsuit < Formula
  desc "Fast, opinionated Terraform naming linter & fixer"
  homepage "https://github.com/josdagaro/tfsuit"
  version "1.3.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josdagaro/tfsuit/releases/download/v1.3.4/tfsuit_1.3.4_darwin_amd64.tar.gz"
      sha256 "7c899e9539281eb3b80a6412c8429e5315501c500727b06f431ae337e2976a8f"

      def install
        bin.install "tfsuit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josdagaro/tfsuit/releases/download/v1.3.4/tfsuit_1.3.4_darwin_arm64.tar.gz"
      sha256 "4b50464cba313abc9cae7e5502bf5d317c5cc377f4c9a1d0f178c82b3ab9292f"

      def install
        bin.install "tfsuit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/josdagaro/tfsuit/releases/download/v1.3.4/tfsuit_1.3.4_linux_amd64.tar.gz"
      sha256 "d273d83bda6a72fac4d3dd3bc6476996a5b9399ecdd191edd2ecc1558b7c4d66"
      def install
        bin.install "tfsuit"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/josdagaro/tfsuit/releases/download/v1.3.4/tfsuit_1.3.4_linux_arm64.tar.gz"
      sha256 "58bb8036745addadda35787756157d92e55c38f3b5cf03117dfd36a625d5a1cb"
      def install
        bin.install "tfsuit"
      end
    end
  end

  test do
    tfsuit --help
  end
end
